server:
  port: 8888
spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/study/native-file-repo
        git:
          #uri: file:///Users/jeff/study/inflearn-spring-cloud-config
          uri: https://github.com/joonYK/inflearn-spring-cloud-config
          #private repository 인 경우
          #username:
          #password:

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh